/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chavez.cesar.agendav2;

/**
 *
 * @author depresionatom
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDP_Principal = new javax.swing.JDesktopPane();
        JMB_Menu = new javax.swing.JMenuBar();
        JM_Inicio = new javax.swing.JMenu();
        JMI_Captura = new javax.swing.JMenuItem();
        JMI_Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDP_PrincipalLayout = new javax.swing.GroupLayout(JDP_Principal);
        JDP_Principal.setLayout(JDP_PrincipalLayout);
        JDP_PrincipalLayout.setHorizontalGroup(
            JDP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JDP_PrincipalLayout.setVerticalGroup(
            JDP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        JM_Inicio.setText("Inicio");

        JMI_Captura.setText("Captura");
        JMI_Captura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CapturaActionPerformed(evt);
            }
        });
        JM_Inicio.add(JMI_Captura);

        JMI_Salir.setText("Salir");
        JM_Inicio.add(JMI_Salir);

        JMB_Menu.add(JM_Inicio);

        jMenu2.setText("Edit");
        JMB_Menu.add(jMenu2);

        setJMenuBar(JMB_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDP_Principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDP_Principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_CapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CapturaActionPerformed
        // TODO add your handling code here:
        
        // Instanciamos el objeto
        Captura ventana = new Captura();
        // Agregamos el objeto a la ventana principal
        JDP_Principal.add(ventana);
        // Manda hacia delante al objeto o a la ventana que instaseamos
        ventana.toFront();
        // Mostramos la pantalla
        ventana.setVisible(true);
    }//GEN-LAST:event_JMI_CapturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDP_Principal;
    private javax.swing.JMenuBar JMB_Menu;
    private javax.swing.JMenuItem JMI_Captura;
    private javax.swing.JMenuItem JMI_Salir;
    private javax.swing.JMenu JM_Inicio;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
